[tool.poetry]
name = "revanced-api"
version = "0.1.0"
description = ""
authors = ["Alexandre Teles <alexandre.teles@ufba.br>"]
license = "AGPLv3"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
aiohttp = {version = "^3.8.5", extras = ["speedups"]}
sanic = {version = "^23.6.0", extras = ["ext"]}
ujson = "^5.8.0"
asyncstdlib = "^3.10.8"
pydantic = "^2.2.0"
cytoolz = "^0.12.2"
beautifulsoup4 = "^4.12.2"
setuptools = "^68.0.0"
lxml = "^4.9.3"
mypy = "^1.5.0"
types-ujson = "^5.8.0.1"
types-aiofiles = "^23.1.0.5"
sanic-testing = "^23.6.0"
pytest-asyncio = "^0.21.1"
types-beautifulsoup4 = "^4.12.0.6"
pytest-md = "^0.2.0"
pytest-emoji = "^0.2.0"
coverage = "^7.3.0"
pytest-cov = "^4.1.0"
pytest = "^7.4.0"

[tool.pytest.ini_options]
asyncio_mode = "auto"
filterwarnings = [
    "ignore::DeprecationWarning",
    "ignore::pytest.PytestCollectionWarning"
    ]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
