[tool.poetry]
name = "revanced-api"
version = "0.1.0"
description = ""
authors = ["Alexandre Teles <alexandre.teles@ufba.br>"]
license = "AGPLv3"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
aiohttp = {version = ">=3.8.4", extras = ["speedups"]}
sanic = {version = ">=23.3.0", extras = ["ext", "http3"]}
ujson = ">=5.7.0"
asyncstdlib = "3.10.6"
pydantic = ">=1.10.7"
aioquic = ">=0.9.20"
cytoolz = ">=0.12.1"
beautifulsoup4 = ">=4.12.2"
setuptools = ">=67.7.2"
lxml = ">=4.9.2"

[tool.poetry.dev-dependencies]
mypy = ">=1.2.0"
types-ujson = ">=5.7.0.5"
types-aiofiles = ">=23.1.0.1"
sanic-testing = ">=23.3.0"
pytest-asyncio = ">=0.21.0"
types-beautifulsoup4 = ">=4.12.0.5"

[tool.pytest.ini_options]
asyncio_mode = "auto"
filterwarnings = [
    "ignore::DeprecationWarning",
    "ignore::pytest.PytestCollectionWarning"
    ]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
